# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

development:
  adapter: postgresql
  encoding: unicode
  database: sistema_hotel
  pool: 5
  username: postgres
  password: 12345

test:
  adapter: postgresql
  encoding: unicode
  database: sistema_hotel_test
  pool: 5
  username: postgres
  password: 12345

  
production:
  adapter: postgresql
  encoding: unicode
  database: sistema_hotel_production
  pool: 5
  username: postgres
  password: 12345